export interface Collection {
    name: string;
    id: string;
    smart_money_inflow_24h: number;
    smart_money_inflow_7d: number;
    slug: string;
    supply: number;
    current_owner_count: number;
    owners_avg_usdc_holdings: number;
    avg_price_sol: number | null;
    avg_price_usd: number | null;
    sol_price_usd: number;
    sol_price_usd_last_updated: number;
    magic_eden_holding: number;
    magic_eden_holding_proportion: number;
    market_cap_usd: number | null;
    market_cap_sol: number | null;
    average_wash_score: number;
    sample_image: string;
    mint_price_mode: number | null;
    narrative: string;
    external_url: string;
    listing_count: number | null;
    granularity: string;
    nrt_price: number;
    nrt_prev_price: number;
    nrt_volume: number;
    nrt_prev_volume: number;
    nrt_price_percent_change: number | null;
    nrt_volume_percent_change: number | null;
    nrt_price_delta: number;
    nrt_volume_delta: number;
  }